### ISSUE TITLE
Bug: AVD-AWS-0082 not detected by trivy anymore

### ISSUE THREAD

**Issue by amascia-gg** [aquasecurity/trivy-policies#78]
Hi trivy team, thank you for your work!

I've seen that you've recently made some big changes between v0.93.1 and v0.94.0 of defsec.
There is this [no_public_db_access.go](https://github.com/aquasecurity/defsec/blob/v0.93.1/rules/cloud/policies/aws/rds/no_public_db_access.go) file that used to exist for AWS RDS (in v0.93.1) which [disappeared](https://github.com/aquasecurity/trivy-policies/tree/9884fb56926f1e2b95406b4782f3fdf4565c4c6f/checks/cloud/aws/rds) in this repository so when running `trivy` (latest version) with the bad example in this [file](https://github.com/aquasecurity/defsec/blob/v0.93.1/rules/cloud/policies/aws/rds/no_public_db_access.tf.go) the vuln is not catched anymore.

**Comment by amascia-gg** [comment]
It looks like it was removed by [this commit](https://github.com/aquasecurity/trivy-policies/commit/a1322dcdc125cabe797b35bf807971680e5706e0) but I don't really see why as AVD-AWS-0180 that replaces it does not have a go file.

**Comment by simar7** [comment]
The rule was re-written in Rego and as you pointed out can be found here: https://github.com/aquasecurity/trivy-policies/blob/main/checks/cloud/aws/rds/disable_public_access.rego hence does not require any Go file.
